// Generated by gencpp from file mur_common/actuation_msg.msg
// DO NOT EDIT!


#ifndef MUR_COMMON_MESSAGE_ACTUATION_MSG_H
#define MUR_COMMON_MESSAGE_ACTUATION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mur_common
{
template <class ContainerAllocator>
struct actuation_msg_
{
  typedef actuation_msg_<ContainerAllocator> Type;

  actuation_msg_()
    : header()
    , acceleration_threshold(0.0)
    , steering(0.0)  {
    }
  actuation_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acceleration_threshold(0.0)
    , steering(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _acceleration_threshold_type;
  _acceleration_threshold_type acceleration_threshold;

   typedef float _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::mur_common::actuation_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mur_common::actuation_msg_<ContainerAllocator> const> ConstPtr;

}; // struct actuation_msg_

typedef ::mur_common::actuation_msg_<std::allocator<void> > actuation_msg;

typedef boost::shared_ptr< ::mur_common::actuation_msg > actuation_msgPtr;
typedef boost::shared_ptr< ::mur_common::actuation_msg const> actuation_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mur_common::actuation_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mur_common::actuation_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mur_common::actuation_msg_<ContainerAllocator1> & lhs, const ::mur_common::actuation_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.acceleration_threshold == rhs.acceleration_threshold &&
    lhs.steering == rhs.steering;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mur_common::actuation_msg_<ContainerAllocator1> & lhs, const ::mur_common::actuation_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mur_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mur_common::actuation_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mur_common::actuation_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mur_common::actuation_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mur_common::actuation_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mur_common::actuation_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mur_common::actuation_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mur_common::actuation_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99957e1c187e5d8438ff90bc231cd730";
  }

  static const char* value(const ::mur_common::actuation_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99957e1c187e5d84ULL;
  static const uint64_t static_value2 = 0x38ff90bc231cd730ULL;
};

template<class ContainerAllocator>
struct DataType< ::mur_common::actuation_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mur_common/actuation_msg";
  }

  static const char* value(const ::mur_common::actuation_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mur_common::actuation_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Timestamp in case EMC needs it\n"
"Header header\n"
"\n"
"# acceleration_threshold goes from [-1, 1], where \n"
"# -1 denotes max. braking and 1 denotes max. acceleration. \n"
"# Anything > 0 is acceleration, while <= 0 should be treated as braking.\n"
"float32 acceleration_threshold\n"
"\n"
"# steering is defined in terms of raw radians value, not threshold.\n"
"float32 steering\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mur_common::actuation_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mur_common::actuation_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acceleration_threshold);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct actuation_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mur_common::actuation_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mur_common::actuation_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration_threshold: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration_threshold);
    s << indent << "steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUR_COMMON_MESSAGE_ACTUATION_MSG_H
