// Generated by gencpp from file mur_common/cone_msg.msg
// DO NOT EDIT!


#ifndef MUR_COMMON_MESSAGE_CONE_MSG_H
#define MUR_COMMON_MESSAGE_CONE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mur_common
{
template <class ContainerAllocator>
struct cone_msg_
{
  typedef cone_msg_<ContainerAllocator> Type;

  cone_msg_()
    : header()
    , x()
    , y()
    , colour()
    , frame_id()  {
    }
  cone_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(_alloc)
    , y(_alloc)
    , colour(_alloc)
    , frame_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_type;
  _x_type x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_type;
  _y_type y;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _colour_type;
  _colour_type colour;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;





  typedef boost::shared_ptr< ::mur_common::cone_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mur_common::cone_msg_<ContainerAllocator> const> ConstPtr;

}; // struct cone_msg_

typedef ::mur_common::cone_msg_<std::allocator<void> > cone_msg;

typedef boost::shared_ptr< ::mur_common::cone_msg > cone_msgPtr;
typedef boost::shared_ptr< ::mur_common::cone_msg const> cone_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mur_common::cone_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mur_common::cone_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mur_common::cone_msg_<ContainerAllocator1> & lhs, const ::mur_common::cone_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.colour == rhs.colour &&
    lhs.frame_id == rhs.frame_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mur_common::cone_msg_<ContainerAllocator1> & lhs, const ::mur_common::cone_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mur_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mur_common::cone_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mur_common::cone_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mur_common::cone_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mur_common::cone_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mur_common::cone_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mur_common::cone_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mur_common::cone_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e84e87d4b24423a16fef8327b191686";
  }

  static const char* value(const ::mur_common::cone_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e84e87d4b24423aULL;
  static const uint64_t static_value2 = 0x16fef8327b191686ULL;
};

template<class ContainerAllocator>
struct DataType< ::mur_common::cone_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mur_common/cone_msg";
  }

  static const char* value(const ::mur_common::cone_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mur_common::cone_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] x\n"
"float32[] y\n"
"string[] colour\n"
"string frame_id\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mur_common::cone_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mur_common::cone_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.colour);
      stream.next(m.frame_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cone_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mur_common::cone_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mur_common::cone_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "colour[]" << std::endl;
    for (size_t i = 0; i < v.colour.size(); ++i)
    {
      s << indent << "  colour[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.colour[i]);
    }
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUR_COMMON_MESSAGE_CONE_MSG_H
