// Generated by gencpp from file mur_common/diagnostic_msg.msg
// DO NOT EDIT!


#ifndef MUR_COMMON_MESSAGE_DIAGNOSTIC_MSG_H
#define MUR_COMMON_MESSAGE_DIAGNOSTIC_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mur_common
{
template <class ContainerAllocator>
struct diagnostic_msg_
{
  typedef diagnostic_msg_<ContainerAllocator> Type;

  diagnostic_msg_()
    : header()
    , compute_times()
    , full_compute_times()
    , avg_times(0.0)
    , full_avg_times(0.0)  {
    }
  diagnostic_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , compute_times(_alloc)
    , full_compute_times(_alloc)
    , avg_times(0.0)
    , full_avg_times(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _compute_times_type;
  _compute_times_type compute_times;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _full_compute_times_type;
  _full_compute_times_type full_compute_times;

   typedef float _avg_times_type;
  _avg_times_type avg_times;

   typedef float _full_avg_times_type;
  _full_avg_times_type full_avg_times;





  typedef boost::shared_ptr< ::mur_common::diagnostic_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mur_common::diagnostic_msg_<ContainerAllocator> const> ConstPtr;

}; // struct diagnostic_msg_

typedef ::mur_common::diagnostic_msg_<std::allocator<void> > diagnostic_msg;

typedef boost::shared_ptr< ::mur_common::diagnostic_msg > diagnostic_msgPtr;
typedef boost::shared_ptr< ::mur_common::diagnostic_msg const> diagnostic_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mur_common::diagnostic_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mur_common::diagnostic_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mur_common::diagnostic_msg_<ContainerAllocator1> & lhs, const ::mur_common::diagnostic_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.compute_times == rhs.compute_times &&
    lhs.full_compute_times == rhs.full_compute_times &&
    lhs.avg_times == rhs.avg_times &&
    lhs.full_avg_times == rhs.full_avg_times;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mur_common::diagnostic_msg_<ContainerAllocator1> & lhs, const ::mur_common::diagnostic_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mur_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mur_common::diagnostic_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mur_common::diagnostic_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mur_common::diagnostic_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mur_common::diagnostic_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mur_common::diagnostic_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mur_common::diagnostic_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mur_common::diagnostic_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86dfa5aa3426c366054b57ad074c89ef";
  }

  static const char* value(const ::mur_common::diagnostic_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86dfa5aa3426c366ULL;
  static const uint64_t static_value2 = 0x054b57ad074c89efULL;
};

template<class ContainerAllocator>
struct DataType< ::mur_common::diagnostic_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mur_common/diagnostic_msg";
  }

  static const char* value(const ::mur_common::diagnostic_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mur_common::diagnostic_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint32[] compute_times # Native code execution time\n"
"uint32[] full_compute_times # Approximate ROS inclusive execution time\n"
"float32 avg_times\n"
"float32 full_avg_times\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mur_common::diagnostic_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mur_common::diagnostic_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.compute_times);
      stream.next(m.full_compute_times);
      stream.next(m.avg_times);
      stream.next(m.full_avg_times);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct diagnostic_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mur_common::diagnostic_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mur_common::diagnostic_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "compute_times[]" << std::endl;
    for (size_t i = 0; i < v.compute_times.size(); ++i)
    {
      s << indent << "  compute_times[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.compute_times[i]);
    }
    s << indent << "full_compute_times[]" << std::endl;
    for (size_t i = 0; i < v.full_compute_times.size(); ++i)
    {
      s << indent << "  full_compute_times[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.full_compute_times[i]);
    }
    s << indent << "avg_times: ";
    Printer<float>::stream(s, indent + "  ", v.avg_times);
    s << indent << "full_avg_times: ";
    Printer<float>::stream(s, indent + "  ", v.full_avg_times);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUR_COMMON_MESSAGE_DIAGNOSTIC_MSG_H
