// Generated by gencpp from file mur_common/timing_msg.msg
// DO NOT EDIT!


#ifndef MUR_COMMON_MESSAGE_TIMING_MSG_H
#define MUR_COMMON_MESSAGE_TIMING_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mur_common
{
template <class ContainerAllocator>
struct timing_msg_
{
  typedef timing_msg_<ContainerAllocator> Type;

  timing_msg_()
    : header()
    , compute_time(0.0)
    , full_compute_time(0.0)  {
    }
  timing_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , compute_time(0.0)
    , full_compute_time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _compute_time_type;
  _compute_time_type compute_time;

   typedef float _full_compute_time_type;
  _full_compute_time_type full_compute_time;





  typedef boost::shared_ptr< ::mur_common::timing_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mur_common::timing_msg_<ContainerAllocator> const> ConstPtr;

}; // struct timing_msg_

typedef ::mur_common::timing_msg_<std::allocator<void> > timing_msg;

typedef boost::shared_ptr< ::mur_common::timing_msg > timing_msgPtr;
typedef boost::shared_ptr< ::mur_common::timing_msg const> timing_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mur_common::timing_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mur_common::timing_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mur_common::timing_msg_<ContainerAllocator1> & lhs, const ::mur_common::timing_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.compute_time == rhs.compute_time &&
    lhs.full_compute_time == rhs.full_compute_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mur_common::timing_msg_<ContainerAllocator1> & lhs, const ::mur_common::timing_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mur_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mur_common::timing_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mur_common::timing_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mur_common::timing_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mur_common::timing_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mur_common::timing_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mur_common::timing_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mur_common::timing_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17ddf4cbaf34e8ded16e85be9c287e6e";
  }

  static const char* value(const ::mur_common::timing_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17ddf4cbaf34e8deULL;
  static const uint64_t static_value2 = 0xd16e85be9c287e6eULL;
};

template<class ContainerAllocator>
struct DataType< ::mur_common::timing_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mur_common/timing_msg";
  }

  static const char* value(const ::mur_common::timing_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mur_common::timing_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float32 compute_time # Native code execution time\n"
"float32 full_compute_time # Approximate ROS inclusive execution time\n"
"# float32 avg_times\n"
"# float32 full_avg_times\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mur_common::timing_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mur_common::timing_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.compute_time);
      stream.next(m.full_compute_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct timing_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mur_common::timing_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mur_common::timing_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "compute_time: ";
    Printer<float>::stream(s, indent + "  ", v.compute_time);
    s << indent << "full_compute_time: ";
    Printer<float>::stream(s, indent + "  ", v.full_compute_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUR_COMMON_MESSAGE_TIMING_MSG_H
